apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homarr-ingress-certificate
  namespace: homarr
spec:
  secretName: homarr-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - homarr.natetech.org