apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:3n8nNnOfeJwZptpzCIgp9w++KZBL+vGT0E5s5+H0AdOm7GB8pEHmxQ==,iv:EPdj2YDQ5Gn43Z2qpbNcdpTsUQacAr2tz4AKQpforQU=,tag:XgMmDKRhfQKRMpdOtpEMZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rmg570p3uqweg0w4fwhq0ndtmhg8tfac8axgajtghuh4dpzc5hsh6uvgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOHJKaWhXZHpjVG9hVkhB
            YlRCaVdYUzYyRFF6c0hMNW9XOTRwN3Z4NEIwCmFselIxY3VncVV1RENtM0VVOXo1
            NSsxVVg2OEdmUjZNaEJ2Y3dFaVRhUGcKLS0tIEdQMmlkaVFBdHVHbFplRXZSeTl1
            MDc1NHFMZW5Oc3Z5Qk5aRHAzTVI4L2MK4MjevKPmTQwRtC0Q5BmKVT8BpNW8VynO
            nxD68z9j41ZcfQD73ihyByjSIgvSzh0GG56aqUhhobNVvaZAHGo0wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-26T03:05:51Z"
    mac: ENC[AES256_GCM,data:l3d/ErCi/OpumQ6QbZPOX4O+hgm/Z0GvrCQl4lzbafUQXzepG6ApXeIfY3jmpyDrWrfNJ3+dwmUq4slnFKdvPlGA2YHHC1JKBNMXT153MDMggir8q1R0KAnfj7e90NJHQx7UpErQCf7xCK2gQq2bcxM8Z3FsYxWaYNWNTzapXTs=,iv:dbo6Rtj38qehjmNvagtIzrFXeyp+NF6Y7v9CKPm9Yb4=,tag:VLK0Y6kVh729RXXDQeHbWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4