apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: navidrome-ingress-certificate
  namespace: navidrome
spec:
  secretName: navidrome-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - navidrome.natetech.org