apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kanboard-ingress-certificate
  namespace: kanboard
spec:
  secretName: kanboard-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - kanboard.natetech.org