apiVersion: v1
kind: Service
metadata:
  name: dbkanboard-service
  namespace: kanboard
spec:
  ports:
  - name: mariadb
    targetPort: 3306
    port: 3306
    protocol: TCP
  selector:
    srv: dbkanboard
---
apiVersion: v1
kind: Service
metadata:
  name: kanboard-service
  namespace: kanboard
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
    protocol: TCP
  - name: https
    targetPort: 443
    port: 443
    protocol: TCP
  type: ClusterIP
  selector:
    run: kanboard