apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  labels:
    srv: dbakanboard
  name: dba-kanboard-cfg
  namespace: kanboard
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: kanboard-data
  namespace: kanboard
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  labels:
    app: kanboard
  name: kanboard-plugins
  namespace: kanboard
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  labels:
    app: kanboard
  name: kanboard-ssl
  namespace: kanboard
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  labels:
    app: kanboard
  name: kanboard-config
  namespace: kanboard
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi