apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homeassistant-ingress-certificate
  namespace: home-assistant
spec:
  secretName: homeassistant-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - ha.natetech.org