apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 4h
  chart:
    spec:
      chart: home-assistant
      version: "0.x.x"
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    ingress:
      enabled: true
      external: false
      className: "traefik"
      hosts:
        - host: ha.natetech.org
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: homeassistant-certificate-secret
          hosts:
            - ha.natetech.org
#    persistence:
#      enabled: false
#      accessMode: ReadWriteOnce
#      size: 1Gi # TODO: change to 5Gi if I deploy to prod- this staging node I don't have much space currently
#      storageClass: "longhorn"