apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: openspeedtest-ingress
  namespace: openspeedtest
spec:
  entryPoints:
    - web
  routes:
    - match: Host('speedtest.natetech.org')
      kind: Rule
      services:
        - name: openspeedtest
          port: 3000