apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openspeedtest-ingress
  namespace: openspeedtest
spec:
  rules:
  - host: "speedtest.natetech.org"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openspeedtest
            port:
              number: 3000