apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:OTVR2ycS2Pg0Rh8a7FjzCJHG9+85DU/1RdNWUJronRkfQ4SeAD8oM8WuBMoOXT1lB8Q8ciyGHe+s5jS/iYYKPWLqiss30Mn1421IV2wfEe06XgITiVF+wPVEr8dn/iIXiu7NTbJw/7Cb7lj/NkkxY2s8ca7dJHqKFEYsxUFURvEVa9oUIEQRzeu8WbmWhz+YaLWbMrvkPof9Z5L6HfmsjrxUp5xtaoLSteq7n4SxzL0LfH2nYWooJ+MxD1JF5rJLMa42kJf2KuXaQm/ATMSCEDH1ph3rc6h6hp83bGA6PEG5MQjVIDjvUavj2+o=,iv:PLWKlq+wat6GdMtQNhdK+ZHDwjme0qQra6dV8Fg0YEk=,tag:ilA9EVLDRHZ0X/RgiXu4kA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12rmg570p3uqweg0w4fwhq0ndtmhg8tfac8axgajtghuh4dpzc5hsh6uvgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZkhTT1RpY1ZZZzJJekl4
            cHlTc1RncGs0SS9jbkVIQ2xoSk5KQWJoQlhzCm1BUEkwSGZvOHljbE00QzlRRTJs
            Y3R6dVhTTmJLSDFwV2FUOFVkL1VjdVEKLS0tIGFmTDdCcEdzSmE0TkoyVXpISzZp
            VExkSTV2R3ZkY3BxbThZMEwzbEJoODQK/eUGTlxARW+8qOCY+xHAN/gB3HxhTrvF
            IydQHVQsZG59TBV2NWJGyLfHYclVicBF4RO+/aNf1OYsSrZaRFM02g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T20:06:03Z"
    mac: ENC[AES256_GCM,data:9kfl6Gv7HPHFd9FaFkynSTxfiEW05UhrFWIf0Zcs7F9OZHPAMMnkFIDLJ/P2Zai51QKv0R3RokSmffYPriY3hZOXqSzXt7lINauyISUpWmhgd+vGXRhoDvFc+n5OoFsm1v6eWKA6H4yTmQ5yMfj2oih7YpohKxTcjmbhLKxUgzA=,iv:IfbIqYTknk2zERaaMw4Xqd0Z7ob2YwzpO/dh6XtAFaM=,tag:zsmxitwWGlKIS1OZvTEDGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
