apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-ingress-certificate
  namespace: homepage
spec:
  secretName: homepage-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - home.natetech.org