apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mealie-ingress-certificate
  namespace: mealie
spec:
  secretName: mealie-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - mealie.natetech.org