apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-ingress-certificate
  namespace: jellyfin
spec:
  secretName: jellyfin-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - jellyfin.natetech.org