apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 4h
  chart:
    spec:
      chart: jellyfin
      version: "jellyfin-2.x.x"
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: jellyfin
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    ingress:
      enabled: true
      className: traefik
      url: jellyfin.natetech.org
    volumeMounts:
      - name: movies
        mountPath: /mnt/movies
        readOnly: true
      - name: tvshows
        mountPath: /mnt/tvshows
        readOnly: true
    volumes:
      - name: movies
        hostPath:
          path: /mnt/movies
          type: Directory
      - name: tvshows
        hostPath:
          path: /mnt/tvshows
          type: Directory