apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Nate Homepage

    background:
      image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
      blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 100 # 0-100

    theme: dark
    color: slate

    useEqualHeights: true

    layout:
      Main:
        header: true
        style: row
        columns: 4
      DNS:
        header: true
        style: row
        columns: 4
      Apps:
        header: true
        style: row
        columns: 6
      Other:
        header: true
        style: row
        columns: 4
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Main
        - Proxmox
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
            description: Greenmachine
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
                username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
                password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
                node: greenmachine
        - Portainer:
            icon: portainer.svg
            href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
            description: docker
            widget:
                type: portainer
                url: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
                env: 2
                key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}"
    - DNS:
        - Pi-Hole1:
            icon: pi-hole.svg
            href: "{{HOMEPAGE_VAR_PIHOLE_URL_1}}"
            description: quasar
            widget:
                type: pihole
                url: "{{HOMEPAGE_VAR_PIHOLE_URL_1}}"
                key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_1}}"
        - Pi-Hole2:
            icon: pi-hole.svg
            href: "{{HOMEPAGE_VAR_PIHOLE_URL_2}}"
            description: blazar
            widget:
                type: pihole
                url: "{{HOMEPAGE_VAR_PIHOLE_URL_2}}"
                key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_2}}"
    - Apps:
        - Open-webui:
            icon: chatgpt.svg
            href: https://chat.natetech.org
            description: Local LLM
        - Linkding
            icon: linkding.svg
            href: https://linkding.natetech.org
            description: Bookmark manager
        - Wekan
            icon: atlassian-jira.svg
            href: https://wekan.natetech.org
            description: Kanban board
    - Other:
        - GitLab:
            icon: gitlab.svg
            href: https://gitlab.com
            description: source code
        - GitHub:
            icon: github.svg
            href: https://github.com
            description: source code
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /

    - datetime:
        text_size: xl
        format:
          timeStyle: short
  docker.yaml: ""