apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-ingress-certificate
  namespace: jellyfin
spec:
  secretName: plex-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - plex.natetech.org