apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wekan-ingress-certificate
  namespace: wekan
spec:
  secretName: wekan-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - wekan.natetech.org