apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openspeedtest-ingress-certificate
  namespace: openspeedtest
spec:
  secretName: openspeedtest-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - speedtest.natetech.org