apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-test-data-pvc
  namespace: nginx-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi