apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:latest
              args:
                - ngresbach11/k3s-homelab
              envFrom:
                - secretRef:
                    name: renovate-token
                - configMapRef:
                    name: renovate-configmap
          restartPolicy: Never